stages:
  - deploy
  - cleanup

deploy-main:
  stage: deploy
  only:
    - main
  script:
    - apt-get update -qq && apt-get install -y lftp
    - lftp -c "
        set ftp:ssl-allow no;
        open -u $FTP_USER,$FTP_PASS $FTP_HOST;
        mirror -R --delete public $FTP_DIR
      "
  environment:
    name: production
  dependencies: []
